// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoMvc.Models;

#nullable disable

namespace ProyectoMvc.Migrations
{
    [DbContext(typeof(Alumnocontext))]
    partial class AlumnocontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoMvc.Models.modelos.Comentario", b =>
                {
                    b.Property<Guid>("ComentarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComentarioTexto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Cursoid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ComentarioId");

                    b.HasIndex("Cursoid");

                    b.ToTable("comentarios");
                });

            modelBuilder.Entity("ProyectoMvc.Models.modelos.Curso", b =>
                {
                    b.Property<Guid>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CursoId");

                    b.ToTable("cursos");
                });

            modelBuilder.Entity("ProyectoMvc.Models.modelos.Comentario", b =>
                {
                    b.HasOne("ProyectoMvc.Models.modelos.Curso", "curso")
                        .WithMany("comentariolista")
                        .HasForeignKey("Cursoid");

                    b.Navigation("curso");
                });

            modelBuilder.Entity("ProyectoMvc.Models.modelos.Curso", b =>
                {
                    b.Navigation("comentariolista");
                });
#pragma warning restore 612, 618
        }
    }
}
